FROM node:20.9-alpine3.18

WORKDIR /home/node/app
COPY . /home/node/app

ENV NODE_ENV=production
EXPOSE 3000
ENV PORT 3000
ENV HOSTNAME "0.0.0.0"

RUN npm i && npm run build
ENTRYPOINT ["npm", "run", "start"]

