version: "3"

services:

  web:
    image: nginx:1.25-alpine3.18
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
    volumes:
      - ./utils/nginx/:/etc/nginx/conf.d/:ro
      - ./utils/certbot/conf:/etc/nginx/ssl:rw
    ports:
      - "80:80"
      - "443:443"
      - "5555:5555"

  certbot:
    image: certbot/certbot:amd64-v2.7.4
    volumes:
      - ./utils/certbot/www/:/var/www/certbot/:rw
      - ./utils/certbot/conf/:/etc/letsencrypt/:rw

  swagger:
    image: swaggerapi/swagger-ui
    environment:
      SWAGGER_JSON: "/config/swagger.json"
    volumes:
      - ./utils/swagger/swagger.json:/config/swagger.json

  frontend:
    image: solestyleimages/frontend

  product_management:
    image: solestyleimages/product_management_service
    environment:
      DOTENV_KEY: ${DOTENV_PRODUCT_MANAGEMENT_KEY}

  account_management:
    image: solestyleimages/account_management_service
    environment:
      DOTENV_KEY: ${DOTENV_ACCOUNT_MANAGEMENT_KEY}

  shopping_cart_management:
    image: solestyleimages/shopping_cart_management
    environment:
      DOTENV_KEY: ${DOTENV_SHOPPING_CART_MANAGEMENT_KEY}

