version: "3.9"  
networks:
  solestyle_network:
    ipam:
      config:
        - subnet: "172.25.0.0/16"


services:

  web:
    image: nginx:1.25-alpine3.18
    volumes:
      - ./utils/nginx/:/etc/nginx/conf.d/
    ports:
      - "80:80"
      - "5555:5555"
    expose:
      - 3000
    networks:
      solestyle_network:
        ipv4_address: "172.25.0.10"


  swagger:
    image: swaggerapi/swagger-ui
    environment:
      SWAGGER_JSON: "/config/swagger.json"
    volumes:
      - ./utils/swagger/swagger.json:/config/swagger.json
    ports:
      - "5555:5555"

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile.dev
    image: solestyle_dev/frontend
    volumes:
      - $PWD/frontend:/home/node/app/
    expose:
      - 3000
    networks:
      solestyle_network:
        ipv4_address: "172.25.0.11"

  product_management:
    build:
      context: backend/product_management
      dockerfile: Dockerfile.dev
    image: solestyle_dev/product_management_service
    expose:
      - 4000
    environment:
      DOTENV_KEY: ${DOTENV_PRODUCT_MANAGEMENT_KEY}
    networks:
      solestyle_network:
        ipv4_address: "172.25.0.12"

  account_management:
    build:
      context: backend/account_management
      dockerfile: Dockerfile.dev
    image: solestyle_dev/account_management_service
    expose:
      - 4500
    environment:
      DOTENV_KEY: ${DOTENV_ACCOUNT_MANAGEMENT_KEY}
    networks:
      solestyle_network:
        ipv4_address: "172.25.0.13"

  shopping_cart_management:
    build:
      context: backend/shoppingCardManagement
      dockerfile: Dockerfile.dev
    image: solestyle_dev/shopping_cart_management
    expose:
      - "5000:5000"
    networks:
      solestyle_network:
        ipv4_address: "172.25.0.14"
