name: 'Testing env deployment'
run-name: ${{ github.actor }} is executing the workflow ${{ github.workflow }}.

on: []

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Send update signal to server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ vars.QA_HOST }}
          username: ${{ secrets.QA_USERNAME }}
          key: ${{ secrets.QA_KEY }}
          script: ./tools/run_images_upgrade

