name: "Backend: Product Management Workflow"
run-name: ${{ github.actor }} is executing the workflow ${{ github.workflow }}.

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - develop
      - main
    paths:
      - "backend/product_management/**"

jobs:
  build:
    name: Build
    runs-on:  ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ vars.GO_VERSION }} 

      - name: Building 
        run: cd backend/product_management && go build -v .


  test:
    name: Test
    needs: build
    runs-on:  ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ vars.GO_VERSION }} 

      - name: Running tests 
        run: cd backend/product_management/test && go test -v .

